[package]
name    = "best_before_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
serde     = { version = "1.0", features = ["derive"] }
time      = { version = "0.3", features = ["serde", "serde-human-readable"] }
actix-web = "4"
config    = "0.13"
